# Generated by Django 4.1.3 on 2022-12-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bissextile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearrange',
            name='year_range',
            field=models.CharField(blank=True, max_length=9999999),
        ),
    ]
