# Generated by Django 4.1.3 on 2022-12-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculatrice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requetes',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculatrice.operation')),
            ],
            bases=('calculatrice.operation',),
        ),
    ]
